# Copyright (C) 2009-2011  Antonio Bonafonte
#            Universitat Politècnica de Catalunya, Barcelona, Spain
#
#  This script is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation,
#  version 2.1 of the License.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

ltsdataTRAINfeatsfn = ltsdataTRAIN.-.feats \
ltsdataTRAIN.a.feats \
ltsdataTRAIN.b.feats \
ltsdataTRAIN.c.feats \
ltsdataTRAIN.d.feats \
ltsdataTRAIN.e.feats \
ltsdataTRAIN.f.feats \
ltsdataTRAIN.g.feats \
ltsdataTRAIN.h.feats \
ltsdataTRAIN.i.feats \
ltsdataTRAIN.j.feats \
ltsdataTRAIN.k.feats \
ltsdataTRAIN.l.feats \
ltsdataTRAIN.m.feats \
ltsdataTRAIN.n.feats \
ltsdataTRAIN.o.feats \
ltsdataTRAIN.p.feats \
ltsdataTRAIN.q.feats \
ltsdataTRAIN.r.feats \
ltsdataTRAIN.s.feats \
ltsdataTRAIN.t.feats \
ltsdataTRAIN.u.feats \
ltsdataTRAIN.v.feats \
ltsdataTRAIN.w.feats \
ltsdataTRAIN.x.feats \
ltsdataTRAIN.y.feats \
ltsdataTRAIN.z.feats \
ltsdataTRAIN.·.feats \
ltsdataTRAIN.à.feats \
ltsdataTRAIN.á.feats \
ltsdataTRAIN.ç.feats \
ltsdataTRAIN.è.feats \
ltsdataTRAIN.é.feats \
ltsdataTRAIN.í.feats \
ltsdataTRAIN.ï.feats \
ltsdataTRAIN.ò.feats \
ltsdataTRAIN.ó.feats \
ltsdataTRAIN.ú.feats \
ltsdataTRAIN.ü.feats
ltsNYtreefn = lts.ñ.tree

