#!/usr/bin/perl -wn
# Purge short words (less or equal to 3 characters), contractions using "'" and
# abbreviations using "."

chomp;

if( ! m/\((".*")\s(.*)\s\((.*)\)$/ ){
    next;
}

my($word, $pos, $trn) = m/\("(.*)"\s(.+)\s\((.*)\)$/;

if( $word =~ /\./ || # skip abbreviatures
    $word =~ /\'/ || # skip contracted articles + pronoms febles
    $word eq "status" || # some weird words appearing in the dictionary
    $word eq "bayern" ||
$word eq "ciència-ficció" ||
$word eq "diürna" ||
$word eq "düsseldorf" ||
$word eq "españa" ||
$word eq "genèticament" ||
$word eq "iñaki" ||
$word eq "muñoz" ||
$word eq "müller" ||
$word eq "núñez" ||
$word eq "prèviament" ||
$word eq "puigcerdà" ||
$word eq "reüll" ||
$word eq "sueño" ||
$word eq "sèriament" ||
$word eq "taüll" ||
$word eq "taüts" ||
$word eq "tècnicament" ||
$word eq "zürich" ||
$word eq "Àfrica" ||
$word eq "Àrtic" ||
$word eq "Àustria" ||
$word eq "Àvila" ||
$word eq "Álvarez" ||
$word eq "Índia" ||
$word eq "Òbviament" ||
$word eq "ciència-ficció" ||
$word eq "croissant" ||
$word eq "cruyff" ||
$word eq "disney" ||
$word eq "diürna" ||
$word eq "düsseldorf" ||
$word eq "edward" ||
$word eq "españa" ||
$word eq "finley" ||
$word eq "genèticament" ||
$word eq "haixix" ||
$word eq "iñaki" ||
$word eq "kelly" ||
$word eq "leyla" ||
$word eq "loyola" ||
$word eq "mayor" ||
$word eq "megabytes" ||
$word eq "muñoz" ||
$word eq "myller" ||
$word eq "müller" ||
$word eq "netscape" ||
$word eq "núñez" ||
$word eq "prèviament" ||
$word eq "puigcerdà" ||
$word eq "rajoy" ||
$word eq "reyes" ||
$word eq "reykiavik" ||
$word eq "reüll" ||
$word eq "rugby" ||
$word eq "sueño" ||
$word eq "sydney" ||
$word eq "sèriament" ||
$word eq "taüll" ||
$word eq "taüts" ||
$word eq "thyssen" ||
$word eq "tsars" ||
$word eq "tècnicament" ||
$word eq "walter" ||
$word eq "washington" ||
$word eq "weissmann" ||
$word eq "wellington" ||
$word eq "whisky" ||
$word eq "whiskys" ||
$word eq "wilson" ||
$word eq "windows" ||
$word eq "yakarta" ||
$word eq "zürich" ||
$word eq "Àfrica" ||
$word eq "Àrtic" ||
$word eq "Àustria" ||
$word eq "Àvila" ||
$word eq "Álvarez" ||
$word eq "Índia" ||
$word eq "Òbviament" ||
$word eq "dawai" ) {
    print STDERR "Skipping $word, too weird!\n";
    next;
}

if( length($word) <= 4 ){
    print STDERR "Skipping $word, too short!\n";
    next;
}

print "$_\n";
