#!/bin/bash

if [ $# -ne 3 ]; then

echo "
 Script to generate LTS rules for Catalan

 Usage:
	$0 allowables.scm dictionary lts_dir

 Input files:
	allowables.scm  --  list of graphemes and possible phonemes
	dictionary	--  dictionary to learn LTS (Festival format)

 Output files:
	lts_dir		--  LTS rules output directory (the Scheme format file
			\"upc_catalan_lts_rules.scm\" will be created there)
";

exit 1;
fi

ALLOWABLES=$1;
DICT=$2;
LTS=$3;

mkdir -p "lts_scratch"

if [ $ALLOWABLES != "allowables.scm" ]; then
	cp $ALLOWABLES allowables.scm;
fi

echo "Prune Festival dictionary prior to Wagon conversion"
./purge_fest_dic < "$DICT" > "$DICT.pruned"

echo "Create multi phonemes" # See readme for more info
./fest2wagon < "$DICT.pruned" > "lts_scratch/lex_entries.out"
#./createmultiphonemes < "$DICT.pruned" > "lts_scratch/lex_entries.out"

echo "Build LTS rules"
./build_lts

mkdir -p "$LTS"
sed -e 's/·/"·"/g' -e 's/lex_lts_rules/upc_catalan_lts_rules/g' "lts_scratch/lex_lts_rules.scm" > "${LTS}/upc_catalan_lts_rules.scm"

echo "Done. File $LTS has been created"


