(require 'lts_build)
(set! allowables 
      '
	((a _epsilon_ a1 ax a2)
        (b _epsilon_ B p b b-b)
        (c _epsilon_ k s g k-s ks)
	(ç _epsilon_ s)
        (d _epsilon_ d D t)
        (e _epsilon_ ax e1 E1 e e2 E2)
        (f _epsilon_ f)
        (g _epsilon_ g G Z tS k dZ d g-g k-s)
        (h _epsilon_)
        (i _epsilon_ i i1 i2 j y)
        (j _epsilon_ Z)
        (k _epsilon_ k)
        (l _epsilon_ l L)
        (m _epsilon_ m)
        (n _epsilon_ n N m J)
        (ñ _epsilon_)
        (o _epsilon_ u o1 O1 o2 O2 o)
        (p _epsilon_ p b b-b)
        (q _epsilon_ k)
        (r _epsilon_ r rr)
        (s _epsilon_ s z)
        (t _epsilon_ t d l m dZ dz)
        (u _epsilon_ u u1 u2 uw w)
        (v _epsilon_ B b)
        (w _epsilon_ B)
        (x _epsilon_ S k ks g g-z tS k-s)
        (y _epsilon_ J)
        (z _epsilon_ z)
        (à _epsilon_ a1)
	(è _epsilon_ E1) 
	(é _epsilon_ e1 e2)
        (í _epsilon_ i1)
	(ò _epsilon_ O1)
	(ó _epsilon_ o1)
	(ú _epsilon_ u1)
	(ü _epsilon_ w)
        (ï _epsilon_ i i1)
    	(· _epsilon_)
 	(- _epsilon_)
        (# #)))
