name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - run: sudo apt-get update
    - run: sudo apt-get install -y --no-install-recommends festival speech-tools perl make perl libxml-libxml-perl
    - run: ./configure
    - run: make build
    - run: make test
